from __future__ import annotations

import time
from datetime import datetime, timezone
import json
import os
from collections import defaultdict
from dataclasses import dataclass
import sqlite3
from typing import Any

import openmeteo_requests
import pandas as pd
import requests_cache
from dotenv import load_dotenv
from openaq import OpenAQ
from retry_requests import retry

# ------------------------------------------------------
# Database setup

DB_NAME = "air_quality2.db" # db with downloaded dataset for ml and fetched data api calls

# creates db if not exist, db should be in the submitted zip
def create_tables():
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()

    # Locations, preloaded in database
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS locations (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT,
        latitude REAL,
        longitude REAL,
        UNIQUE(latitude, longitude)
    )
    """)

    # Stations (actual monitoring stations)
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS stations (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        location_id INTEGER,
        station_api_id INTEGER,   -- ID from OpenAQ (or your API)
        name TEXT,
        latitude REAL,
        longitude REAL,
        FOREIGN KEY (location_id) REFERENCES locations(id)
    )
    """)

    # location level air quality with selected relevant data incl. units
    # here timestamp was set to current time stamp to avoid many missing values
    # because most stations only measure every few days (-> Limitation)
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS air_quality (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        location_id INTEGER,

        pm25 REAL,
        pm10 REAL,
        o3 REAL,

        units_pm25 TEXT,
        units_pm10 TEXT,
        units_o3 TEXT,

        station_count INTEGER,  -- how many stations contributed

        timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,

        FOREIGN KEY (location_id) REFERENCES locations(id),
        UNIQUE(location_id, timestamp)
    )
    """)    # station count -> we set a limit of max. 3 stations per location and only included stations
            # in a radius of 25km that measure all 3 features to avoid missing data

    # weather_daily includes historical data and forecast from API
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS weather_daily (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        location_id INTEGER,

        date DATETIME,
        temperature_mean REAL,
        relative_humidity_mean REAL,

        FOREIGN KEY (location_id) REFERENCES locations(id),
        UNIQUE(location_id, date)
    )
    """)

    conn.commit()
    conn.close()

# ------------------------------------------------------
# Database interaction

# inserts a location into the database and returns the created row.
# if the location already exists, the insert is ignored and the existing location is returned.
# Debugged with ChatGPT
def insert_locations(conn, coordinates):
    cursor = conn.cursor()
    location_ids = {}

    for lon, lat in coordinates:

        cursor.execute("""
            INSERT OR IGNORE INTO locations (name, latitude, longitude)
            VALUES (?, ?, ?)
        """, (f"{lat},{lon}", lat, lon))

        cursor.execute("""
            SELECT id FROM locations
            WHERE latitude = ? AND longitude = ?
        """, (lat, lon))

        row = cursor.fetchone()
        if row:
            location_ids[(lon, lat)] = row[0]

    return location_ids

# Inserts a list of stations into the database
# Generated by ChatGPT
def insert_stations(conn, station_map, location_ids):
    cursor = conn.cursor()

    for key, stations in station_map.items():
        lon, lat = map(float, key.split(","))
        location_id = location_ids[(lon, lat)]

        for station in stations:
            cursor.execute("""
                INSERT OR IGNORE INTO stations (
                    location_id, station_api_id, name
                )
                VALUES (?, ?, ?)
            """, (
                location_id,
                station["id"],
                station["name"],
            ))

# extracts air quality measurement information from station readings and inserts them into the db
# generated by ChatGPT
def insert_air_quality_measurements(conn, results, location_ids):
    cursor = conn.cursor()

    for entry in results:
        lon, lat = entry.coordinate
        agg = entry

        readings = agg.readings
        station_count = agg.station_count

        location_id = location_ids[(lon, lat)]

        pm25 = readings.get("pm25")
        pm10 = readings.get("pm10")
        o3 = readings.get("o3")

        # helper functions to extract the correct properties
        def val(x): return x.value if x else None
        def unit(x): return x.units if x else None

        timestamp = datetime.now(timezone.utc).isoformat()

        cursor.execute("""
            INSERT OR IGNORE INTO air_quality (
                location_id,
                pm25, pm10, o3,
                units_pm25, units_pm10, units_o3,
                station_count,
                timestamp
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            location_id,
            val(pm25), val(pm10), val(o3),
            unit(pm25), unit(pm10), unit(o3),
            station_count,
            timestamp,
        ))

def insert_weather_measurements(conn, weather_results, location_ids):
    cursor = conn.cursor()

    for (lon, lat), data in zip(location_ids.keys(), weather_results.values()):
        location_id = location_ids[(lon, lat)]

        # daily forecast/history
        daily_df = data["daily"]

        for _, row in daily_df.iterrows():
            cursor.execute("""
                INSERT OR IGNORE INTO weather_daily (
                    location_id,
                    date,
                    temperature_mean,
                    relative_humidity_mean
                )
                VALUES (?, ?, ?, ?)
            """, (
                location_id,
                row["date"].strftime("%Y-%m-%d %H:%M:%S"),
                row["temperature_mean"],
                row["relative_humidity_mean"],
            ))

# ---------------------------------------------------------------------------
# Data Transfer Objects to map the API objects to our internal logic
# Structured and generated by ChatGPT

@dataclass
class Reading:
    """A single averaged sensor reading for one parameter."""
    value: float
    units: str | None


@dataclass
class Station:
    """A monitoring station near a queried coordinate."""
    id: int
    name: str | None
    locality: str | None
    country_code: str | None
    country_name: str | None
    provider: str | None
    latitude: float | None
    longitude: float | None


@dataclass
class AggregatedReadings:
    """Averaged readings across one or more stations."""
    station_count: int
    readings: dict[str, Reading]  # parameter name → Reading, in requested order


@dataclass
class CoordinateReadings:
    """Averaged readings for a single queried coordinate."""
    coordinate: tuple[float, float]
    station_count: int
    readings: dict[str, Reading]  # parameter name → Reading, in requested order

# ------------------------------------------------------
# Ingestion

def ingest():
    create_tables()

    coords = [
        (2.3522, 48.8566), # Paris
        (8.5417, 47.3769), # Zurich
        (13.4050, 52.5200), # Berlin
        (-0.1278, 51.5074), # London
        (8.6821, 50.1109), # Frankfurt
        (4.3517, 50.8503), # Brussels
        (18.0686, 59.3293), # Stockholm
    ]

    # load station cache
    with open("stations.json") as f:
        station_map = json.load(f)

    # open a connection
    conn = sqlite3.connect(DB_NAME)

    # locations
    location_ids = insert_locations(conn, coords)

    # stations
    insert_stations(conn, station_map, location_ids)

    # fetch data and insert measurements
    get_fresh_air_quality_measurements(conn, coords, location_ids)
    ingest_weather(conn, coords, location_ids)

    conn.commit()
    conn.close()

    print("Ingestion complete") # for confirmation purposes

# ------------------------------------------------------
# Rate limiter
# because OpenAQ rate limits to 60/min and 2000/hr
# generated with ChatGPT

class RateLimiter:
    def __init__(self, min_interval=1.1):
        self.min_interval = min_interval
        self.last_call = 0

    def wait(self):
        now = time.time()
        elapsed = now - self.last_call
        if elapsed < self.min_interval:
            time.sleep(self.min_interval - elapsed)
        self.last_call = time.time()

# ------------------------------------------------------
# Air quality API

PARAMETERS = ["o3", "pm25", "pm10"]

# fetches air quality readings for a list of locations
# Based on API documentation, adapted and debugged with ChatGPT
def fetch_air_quality(
    coordinates: list[tuple[float, float]],
    radius: int,
    limit: int,
    parameters: list[str],
) -> list[CoordinateReadings]:
    """
    Fetch averaged air-quality readings near one or more coordinates.

    Combines find_stations and fetch_readings_by_ids in a single call,
    reusing one API connection across all coordinates.

    Args:
        coordinates: List of (longitude, latitude) pairs to query.
        radius:      Search radius in metres, applied to every coordinate.
        limit:       Maximum number of stations to consider per coordinate.
        parameters:  Parameter names to include, e.g. ["o3", "pm25", "pm10"].
                     Output readings follow this order; names are normalised
                     to lowercase.

    Returns:
        One CoordinateReadings per input coordinate with:
        - coordinate:    the (lon, lat) pair
        - station_count: number of stations that contributed readings
        - readings:      parameter name → Reading (value + units),
                         in the order given by parameters
    """
    params_ordered = list(dict.fromkeys(_normalize(p) for p in parameters))
    param_set = set(params_ordered)

    # https://python.openaq.org/how-to-guides/geospatial-queries/
    with OpenAQ(api_key=_get_api_key()) as client:
        results = []
        for coordinate in coordinates:
            stations = _list_stations(client, coordinate, radius, limit)
            agg = _aggregate_by_ids(client, [s.id for s in stations], params_ordered, param_set)
            results.append(CoordinateReadings(
                coordinate=coordinate,
                station_count=agg.station_count,
                readings=agg.readings,
            ))
        return results

# fetches and inserts fresh air quality measurements using the fetch_air_quality function
def get_fresh_air_quality_measurements(conn, coordinates, location_ids):
    results = fetch_air_quality(
        coordinates=coordinates,
        radius=20000,
        limit=5,
        parameters=PARAMETERS,
    )

    insert_air_quality_measurements(conn, results, location_ids)

def _get_api_key() -> str:
    load_dotenv()
    key = os.getenv("OPENAQ_API_KEY")
    if not key:
        raise EnvironmentError("OPENAQ_API_KEY is not set in environment / .env file")
    return key

# normalizes strings to remove leading and trailing whitespaces and converts them to lowercase only
# helps our internal data structure look for duplicates
# idea by ChatGPT
def _normalize(name: Any) -> str | None:
    if name is None:
        return None
    return str(name).strip().lower()

# used to find suitable stations for locations
# https://python.openaq.org/how-to-guides/geospatial-queries/#point-and-radius
def _list_stations(
    client: OpenAQ,
    coordinate: tuple[float, float],
    radius: int,
    limit: int,
) -> list[Station]:
    lon, lat = coordinate
    resp = client.locations.list(
        coordinates=(lat, lon),
        radius=radius,
        limit=limit,
    ).dict()

    # Taking relevant data from client result
    # Help from ChatGPT to work with data transfer object
    stations = []
    for loc in resp.get("results") or []:
        country = loc.get("country") or {}
        provider = loc.get("provider") or {}
        coords = loc.get("coordinates") or {}
        stations.append(Station(
            id=loc.get("id"),
            name=loc.get("name"),
            locality=loc.get("locality"),
            country_code=country.get("code"),
            country_name=country.get("name"),
            provider=provider.get("name"),
            latitude=coords.get("latitude"),
            longitude=coords.get("longitude"),
        ))
    return stations

# fetches air quality data for list of station and aggregates to data transfer object
# Generated by ChatGPT based on documentation and previous code
def _aggregate_by_ids(
    client: OpenAQ,
    station_ids: list[int],
    params_ordered: list[str],
    param_set: set[str],
    limiter: RateLimiter | None = None,
) -> AggregatedReadings:

    all_rows: list[dict[str, Any]] = []
    station_count = 0

    for i, station_id in enumerate(station_ids, start=1):
        print(f"[{i}/{len(station_ids)}] Station {station_id}")

        if limiter:
            limiter.wait()

        sensors = client.locations.sensors(station_id).dict().get("results") or []

        rows = []
        for s in sensors:
            param = _normalize((s.get("parameter") or {}).get("name"))
            if param not in param_set:
                continue

            latest = s.get("latest") or {}
            value = latest.get("value")

            if value is None:
                continue

            rows.append({
                "parameter_name": param,
                "units": (s.get("parameter") or {}).get("units"),
                "value": value,
            })

        if rows:
            all_rows.extend(rows)
            station_count += 1

    return AggregatedReadings(
        station_count=station_count,
        readings=_average_by_parameter(all_rows, params_ordered),
    )

# takes measurements of each location and avarages it so that we only have one output per parameter and location
# Improved by ChatGPT
def _average_by_parameter(
    rows: list[dict[str, Any]],
    params_ordered: list[str],
) -> dict[str, Reading]:
    """Average non-null values per parameter and return in requested order."""
    groups: dict[str, list[float]] = defaultdict(list)
    units_map: dict[str, str | None] = {}

    for row in rows:
        param = row.get("parameter_name")
        value = row.get("value")
        if param is None:
            continue
        if value is not None:
            groups[param].append(value)
        units_map.setdefault(param, row.get("units"))

    return {
        p: Reading(value=sum(groups[p]) / len(groups[p]), units=units_map.get(p))
        for p in params_ordered
        if groups[p]
    }

# ------------------------------------------------------
# Weather API

# Setup client
# Generated by ChatGPT
def create_openmeteo_client():
    cache_session = requests_cache.CachedSession(
        '.cache',
        expire_after=3600
    )
    retry_session = retry(cache_session, retries=5, backoff_factor=0.2)
    return openmeteo_requests.Client(session=retry_session)

# Core fetch function (single location)
# Code adapted from API documentation, no API key required
def fetch_weather(client, lat, lon, timezone="Europe/Berlin", past_days=28, forecast_days=14):
    url = "https://api.open-meteo.com/v1/forecast"

    params = {
        "latitude": lat,
        "longitude": lon,
        "daily": [
            "temperature_2m_mean",
            "relative_humidity_2m_mean"
        ],
        "timezone": timezone,
        "past_days": past_days,
        "forecast_days": forecast_days,
    }

    responses = client.weather_api(url, params=params)
    response = responses[0]

    # Daily data -> one API call returns data for 28 days in the past and 14 days forecast
    # Code here from API documentation and debugged/rewritten with ChatGPT
    daily = response.Daily()

    dates = pd.date_range(
        start=pd.to_datetime(
            daily.Time() + response.UtcOffsetSeconds(),
            unit="s",
            utc=True
        ),
        end=pd.to_datetime(
            daily.TimeEnd() + response.UtcOffsetSeconds(),
            unit="s",
            utc=True
        ),
        freq=pd.Timedelta(seconds=daily.Interval()),
        inclusive="left"
    )
    # create df with fetched data
    daily_df = pd.DataFrame({
        "date": dates,
        "temperature_mean": daily.Variables(0).ValuesAsNumpy(),
        "relative_humidity_mean": daily.Variables(1).ValuesAsNumpy(),
    })

    return {
        "coordinates": (response.Latitude(), response.Longitude()),
        "elevation": response.Elevation(),
        "timezone": response.Timezone(),
        "timezone_abbreviation": response.TimezoneAbbreviation(),
        "utc_offset_seconds": response.UtcOffsetSeconds(),
        "daily": daily_df
    }

# gets weather information for a list of locations
def fetch_weather_batch(locations):
    results = {}

    client = create_openmeteo_client()

    for loc in locations:
        name = loc.get("name", f"{loc['lat']},{loc['lon']}")

        # fetch_weather for each location available in locations
        results[name] = fetch_weather(
            client,
            lat=loc["lat"],
            lon=loc["lon"]
        )

    return results

# fetches and inserts weather information
def ingest_weather(conn, coordinates, location_ids):
    results = fetch_weather_batch(
        [
            {"lat": lat, "lon": lon}
            for lon, lat in coordinates
        ]
    )

    insert_weather_measurements(conn, results, location_ids)

# Standalone mode for this file
if __name__ == "__main__":
    ingest()